# Install pre-commit hooks via
# pre-commit install
repos:
 
# yapf = yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.31.0
  hooks:
  - id: yapf
    language: system
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
